Default: &defaults
  database: SimpleDB.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: SimpleDB_test.sqlite3
  <<: *defaults

Staging:
  database: SimpleDB_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: SimpleDB_production.sqlite3
  poolsize: 100
  <<: *defaults
